version: '3.8'

services:
  wireless-network-app:
    build: .
    ports:
      - "8080:80"
    environment:
      - GOOGLE_AI_API_KEY=AIzaSyDYtMsHRiyQSWdta0HxuJ-rC1lCWOId80U
      - FLASK_ENV=production
      - FLASK_DEBUG=False
    volumes:
      - ./logs:/var/log
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  logs:

